// jshint ignore: start
var antlr4 = require('antlr4/index');

// This class defines a complete listener for a parse tree produced by varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Parser.
function varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener() {
	antlr4.tree.ParseTreeListener.call(this);
	return this;
}

varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener.prototype = Object.create(antlr4.tree.ParseTreeListener.prototype);
varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener.prototype.constructor = varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener;

// Enter a parse tree produced by varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Parser#varDecl.
varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener.prototype.enterVarDecl = function(ctx) {
};

// Exit a parse tree produced by varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Parser#varDecl.
varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener.prototype.exitVarDecl = function(ctx) {
};


// Enter a parse tree produced by varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Parser#type.
varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener.prototype.enterType = function(ctx) {
};

// Exit a parse tree produced by varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Parser#type.
varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener.prototype.exitType = function(ctx) {
};



exports.varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener = varDecl_typeID_Q___Q_NUMBER_Q___Q__type__Q_float_Q___Q_int_Q__ID_LETTER_LPAR_LETTER__0_9__RPAR__STAR__fragmentLETTER__a_zA_Z__NUMBER_DIGIT_PLUS__fragmentDIGIT__0_9__SPACES___BS_u000B_BS_t_BS_r_BS_n__ARRW_channel_LPAR_HIDDEN_RPAR_Listener;