// Generated by make_js.py in antlr4-autosuggest project.
const autosuggest = require('../autosuggest');

describe('Autosuggest', function () {
    function DummyObj(lexerCtr, parserCtr) {
    }
    DummyObj.prototype.constructor = DummyObj;

    it('Should throw on lexer without ATN property', function () {
        let ctr = DummyObj.prototype.constructor;
        expect(() => {
            autosuggest.autosuggester(ctr, ctr);
        }).toThrow('Please use ANTLR4 version 4.7.1 or above.');
    });
});
